# Generated by Django 4.2.7 on 2025-07-21 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0002_initial"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistentry",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_entries",
                to="tickets.tickettype",
            ),
        ),
    ]
