# Generated by Django 4.2.7 on 2025-07-21 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("tickets", "0001_initial"),
        ("bookings", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookingstatushistory",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="bookingstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookingnote",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="bookingnote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookingitem",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="bookingitem",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_items",
                to="tickets.tickettype",
            ),
        ),
        migrations.AddField(
            model_name="bookingguest",
            name="assigned_ticket",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_guest",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="bookingguest",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guests",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="payments.discountcode",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="waitlistentry",
            index=models.Index(
                fields=["event", "ticket_type"], name="waitlist_en_event_i_c8bf87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waitlistentry",
            index=models.Index(
                fields=["position"], name="waitlist_en_positio_fcd85e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waitlistentry",
            index=models.Index(
                fields=["is_active"], name="waitlist_en_is_acti_d83080_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="waitlistentry",
            unique_together={("event", "ticket_type", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="bookingitem",
            unique_together={("booking", "ticket_type")},
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_reference"], name="bookings_booking_4d53ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["event"], name="bookings_event_i_d1c541_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["user"], name="bookings_user_id_fdc49e_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="bookings_status_51373b_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["payment_status"], name="bookings_payment_3ea9ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["created_at"], name="bookings_created_118d3e_idx"
            ),
        ),
    ]
