# Generated by Django 4.2.7 on 2025-07-21 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tickets", "0001_initial"),
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettransfer",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tickettransfer",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferred_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tickettransfer",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="tickettransfer",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketaddonpurchase",
            name="addon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="tickets.ticketaddon",
            ),
        ),
        migrations.AddField(
            model_name="ticketaddonpurchase",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addon_purchases",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="ticketaddon",
            name="applicable_ticket_types",
            field=models.ManyToManyField(
                blank=True, related_name="addons", to="tickets.tickettype"
            ),
        ),
        migrations.AddField(
            model_name="ticketaddon",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_addons",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="checked_in_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checked_in_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="current_holder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="held_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="original_buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="original_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="tickets.tickettype",
            ),
        ),
        migrations.AddIndex(
            model_name="tickettype",
            index=models.Index(fields=["event"], name="ticket_type_event_i_802d9e_idx"),
        ),
        migrations.AddIndex(
            model_name="tickettype",
            index=models.Index(
                fields=["sale_status"], name="ticket_type_sale_st_a83066_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tickettype",
            index=models.Index(
                fields=["sale_starts", "sale_ends"],
                name="ticket_type_sale_st_eed075_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticketaddonpurchase",
            unique_together={("ticket", "addon")},
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["ticket_code"], name="tickets_ticket__2ef6a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["event"], name="tickets_event_i_f58fa0_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["status"], name="tickets_status_fbbf05_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["current_holder"], name="tickets_current_e7b3e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["is_checked_in"], name="tickets_is_chec_1de68d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("event", "seat_number", "row_number", "section")},
        ),
    ]
