# Generated by Django 4.2.7 on 2025-07-21 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("bookings", "0004_initial"),
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlement",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settlements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="settlement",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settlements",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="settlement",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_settlements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_refunds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="original_payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refunds",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="refunded_to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_refunds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="applicable_ticket_types",
            field=models.ManyToManyField(
                blank=True, related_name="discount_codes", to="tickets.tickettype"
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_discount_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_codes",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="target_user_groups",
            field=models.ManyToManyField(
                blank=True, help_text="Specific user groups eligible", to="auth.group"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["refund_reference"], name="refunds_refund__0c731e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["original_payment"], name="refunds_origina_62f281_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["status"], name="refunds_status_2569d8_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["refunded_to_user"], name="refunds_refunde_b8d424_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentattempt",
            unique_together={("payment", "attempt_number")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["transaction_reference"], name="payments_transac_4c44f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["booking"], name="payments_booking_4c4815_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_status_d621e5_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_gateway"], name="payments_payment_1e82f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["gateway_transaction_id"], name="payments_gateway_f512b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="payments_payment_aebcb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["is_settled"], name="payments_is_sett_8f1864_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(fields=["code"], name="discount_co_code_085c69_idx"),
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(fields=["event"], name="discount_co_event_i_8ca54e_idx"),
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(
                fields=["valid_from", "valid_until"],
                name="discount_co_valid_f_b1a47b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(
                fields=["is_active"], name="discount_co_is_acti_f4e7bc_idx"
            ),
        ),
    ]
